import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SecaoLateral from "./components/secaoLateral/SecaoLateral";
import Header from "./components/headers/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lista Barata",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header/>
        {children}
        <SecaoLateral/>
      </body>
    </html>
  );
}
